### ISSUE TITLE
Sign In to Continue - Continue as Guest - správné přesměrování?

### ISSUE THREAD

**Issue by nesnera** [gislab-npo/gisquick#103]
Tlačítko `Continue as Guest` vrací na stránku https://projects.gisquick.org/. Má to tak být?

**Comment by marcel-dancak** [comment]
Continue as Guest je v podstate len pre zatvorenie login okna, a malo by sa zobrazovať iba pri verejných projektoch, ak neprihlásený používateľ klikne na login. URL by sa nemala nijako meniť.
