### ISSUE TITLE
Crashing with long user name

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gisquick#21]
Web is crashing when long user name is taken from LDAP.

Sep 8 10:32:10 server postgres[31621]: [2-1] 2015-09-08 10:32:10 CEST ERROR: value too long for type character varying(30)
Sep 8 10:32:10 server postgres[31621]: [2-2] 2015-09-08 10:32:10 CEST STATEMENT: UPDATE "viewer_gislabuser" SET "password" = '', "last_login" = '2015-09-08 08:30:44.116671+00:00', "is_superuse
r" = true, "username" = 'gislab', "first_name" = 'Ivan', "last_name" = 'Mincik [GIS.lab ID: gislab_vagrant]', "email" = 'ivan.mincik@gmail.com', "is_staff" = true, "is_active" = true, "date_join
ed" = '2015-09-08 08:30:44.116807+00:00' WHERE "viewer_gislabuser"."id" = 2

**Comment by landam** [comment]
This issue seems to be GIS.lab related. Closing.
