### ISSUE TITLE
NG

### ISSUE THREAD

**Issue by marcel-dancak** [gislab-npo/gisquick#3]
# GIS.lab Web New Generation
## TODO
- disable drawings support on server - (urls, model, views)
- remove drawings support from gislab-backup| restore
## Technologies
- OpenLayers 3
- Angular 1.4
- Django 1.8
### Empty project
- Base maps - OpenStreetMap (different flavours)
### Base maps
- WMS and WMTS layers
- OpenStreet map - many different flavours, see: https://github.com/imincik/qgis2web/blob/master/basemaps.py
- NO Google maps
- many other free base maps - MapBox, MapQuest, CartoDB, Bing
- custom base maps by specifying Title, URL, URL format (by secifying X,Y,Z variables), token
- transparency
### Overlay layers
- non-cached as WMS
- cached TMS tiles
- layer metadata
### Legend
- symbols filtering on current BBOX
### Attribute table
- will be launched from layer tree
- each column will contain filtering widget on top with data type validation
- all non-empty values from filter will be joined with AND logical operator
- using WFS request
### Measure
- coordinates
- distance
- area
### Identify
- using WFS request
- by point
- enabled as default tool
- possibility to choose active layer or all layers
### Search/Filter
- by filter in attribute table
- using WFS request #462 462
### Cutomization (optional)
- by saving CSS and JS files with project (custom/css/_.css, custom/js/_.js)
- feature detail templates (custom/layer/LAYER_NAME/template) 
### OWS Requests
- running WMS and WFS request on published QGIS project

**Comment by landam** [comment]
Most of functionality already implemented in Gisquick.
