### ISSUE TITLE
QGIS Plugin: Special settings in Project Properties

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gisquick#36]
Before QGIS project publishing it is important to set in Project Properties:

1.) OWS server --> Service capabilities --> Keyword list, e.g. `<some value>`
2.) OWS server --> WMS capabilitie 
- [x] Add geometry to feature response

3.) OWS server --> WFS and WCS capabilities --> 
- [x] Published layers or `Select all`

and also manually set sources to *.svg styles if any exist

Note: Size of symbol has to be set in _mm_ or _px_, can't be set in _map units_

Without settings mentioned above point layers are displayed as question marks, symbols in legend are very large and attribute table is not displayed.

**Comment by lfurtkevicova** [comment]
see [prague.tar.gz](https://github.com/lfurtkevicova/gislab-my-notes/blob/master/prague.tar.gz) and publish it as 

``https://localhost:8000/?PROJECT=vagrant/prague/prague``

**Comment by landam** [comment]
Moved to https://github.com/gislab-npo/gisquick-qgis-plugin/issues/1
