### ISSUE TITLE
QGIS plugin: New topic added twice

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gisquick#39]
Description of situation:

I add `New topic` e.g. "A", then "B", "C", etc. by `Add button`. When I go next by `Next` button, then I return and add new topic "D", it is OK, but when I go back by `Back` button and then I add new topic, `New topic` has twin, see figure below. When I want to delete it, both are deleted after one click on `Remove` button.

![glw-new-topics](https://cloud.githubusercontent.com/assets/13394357/14488422/7edaab4a-0168-11e6-9fa1-11d1f953f549.png)

**Comment by landam** [comment]
Moved to https://github.com/gislab-npo/gisquick-qgis-plugin/issues/2
