### ISSUE TITLE
QGIS plugin: IndexError, list index out of range when all topics are deleted

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gisquick#40]
When list of topics is empty and `Remove` button is pressed, this error is displayed:

![an error has occurred while executing python code _003](https://cloud.githubusercontent.com/assets/13394357/14488593/49dfc5fa-0169-11e6-8908-162ff84b2ae2.png)

I suggest to display e.g. some note or message to inform user that there is nothing else to be removed
instead of this error message.

**Comment by landam** [comment]
Moved to https://github.com/gislab-npo/gisquick-qgis-plugin/issues/3
