### ISSUE TITLE
Is GISQuick a part of GSOC 2018?

### ISSUE THREAD

**Issue by daas-ankur-shukla** [gislab-npo/gisquick#48]
Will GISQuick be a part of GSOC 2018? I am postgraduate student of Geoinformatics and would like to work for GISQuick for GSOC 2018. Kindly provide some contact details of the mentors and starters for beginning the process.

**Comment by daas-ankur-shukla** [comment]
@landam sir i tried to contact you on your mail account. However I am not sure I had used the correct mail address. Kindly provide me some information regarding the project. I am currently doing a project in which i am developing a interoperable web client for OGC standard services (WMS, WFS, etc). 
I believe I am a good fit for this organization.

**Comment by landam** [comment]
Yes, we are going to participate, see https://github.com/gislab-npo/gisquick/wiki/GSoC-Ideas. Feel free to come with your own ideas (e.g someone could test Gisquick with QGIS3 Server). There is also new VUE client under development. We are planning to set up mailing list in near future where topic could be discussed. Stay tuned.

**Comment by daas-ankur-shukla** [comment]
@landam I am glad to read your reply. I am really intrigued to read the idea at [GSoC-Ideas](https://github.com/gislab-npo/gisquick/wiki/GSoC-Ideas) page. As I have mentioned above, I am post-graduate student of Geoinformatics and have undertaken a master's level course on GIS concepts. I am currently enrolled in a course [Advances in Geospatial Standards, Interoperability and Knowledge Discovery](http://www.csre.iitb.ac.in/gnr629.php). The latter course covers Interoperability concepts and we are going through OGC specifications in detail. In the same course I am also developing a Web Client application (Javascript) for interoperable GIS servers. I are working on adding WMS, WFS and WCS functionalities in the current phase. The similarity to my course structure and the nature of the project has motivated me to work for it. As a background experience I have developed a prototype application for map visualization for a smart-parking scenario using **Vanilla Javascript**, **OpenLayers**, & **Django** ([Github Repo](https://github.com/daas-ankur-shukla/Smart-Park), [Selected Abstract](http://www.foss4g-asia.org/2017/open-source-smart-parking-application-using-internet-of-things-and-pgrouting/)). This work was selected as one of the best papers presented in [FOSS4G Asia](http://www.foss4g-asia.org).

**I would love to start discussing ideas and solving issues right away.**
