### ISSUE TITLE
move the opacity tool

### ISSUE THREAD

**Issue by jachym** [gislab-npo/gisquick#64]
move opacity tool to be permanently available to users, not as on-demand tool

current state: 
![obrazek](https://user-images.githubusercontent.com/1460823/60512791-d65e9280-9cd5-11e9-8416-229353b877f6.png)

proposal:
![obrazek](https://user-images.githubusercontent.com/1460823/60512975-5127ad80-9cd6-11e9-8a41-662866c3cfa0.png)

**Comment by marcel-dancak** [comment]
Done.
