### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by karelMT** [gislab-npo/gisquick#75]
GQ have problem with browser Microsoft Edge. There is empty menu without layers and others.

**Comment by marcel-dancak** [comment]
I could check it out tomorrow, but current web application will be replaced with a new one anyway.  Microsoft Edge shouldn't be a problem, just support for IE11 and older will be probably dropped out.

**Comment by marcel-dancak** [comment]
It would require more debugging to find exact problem in MS Edge. I have also tested new unfinished version of web app, and there was only small layout issue with one panel in MS Edge. Overall there may be more bugs in older version, so it's probably better to focus on new version only.

**Comment by marcel-dancak** [comment]
Current development version should work in Microsoft Edge
