### ISSUE TITLE
installation issue with $ docker-compose up

### ISSUE THREAD

**Issue by faustoarch** [gislab-npo/gisquick#81]
Hi,
i get this error whit **$ sudo docker-compose up**:
**nginx_1       | /bin/sh: 1: cannot open /etc/nginx/gisquick/conf.template: No such file**

_ubuntu 18_
Hope someone can help me...Thanks!
___________________________________________________
`Creating network "fausto_default" with the default driver
Pulling go (gisquick/settings:latest)...
latest: Pulling from gisquick/settings
050382585609: Pull complete
62ba64fbaf35: Pull complete
528e63fca6ad: Pull complete
b9a35734c8d3: Pull complete
Digest: sha256:0cca925b6d1c24e3db401e83c55824d420dc0343bd5bd9cebd7fdb28e4524f2c
Status: Downloaded newer image for gisquick/settings:latest
Pulling qgisserver (gisquick/qgis-server:3.4)...
3.4: Pulling from gisquick/qgis-server
35c102085707: Pull complete
251f5509d51d: Pull complete
8e829fe70a46: Pull complete
6001e1789921: Pull complete
15afec5c6b9f: Pull complete
498977a0b992: Pull complete
7adc34b21b84: Pull complete
55834969efe2: Pull complete
26c24b033f4f: Pull complete
096497b3c77c: Pull complete
1b0b518d3a85: Pull complete
Digest: sha256:4e8de4ce7ff35246c789890d99dbfbf687d16fdff55e6126ae5fefa1c68b75af
Status: Downloaded newer image for gisquick/qgis-server:3.4
Pulling django (gisquick/django:vue)...
vue: Pulling from gisquick/django
35c102085707: Already exists
251f5509d51d: Already exists
8e829fe70a46: Already exists
6001e1789921: Already exists
2f0b952d51b5: Pull complete
bb168790b196: Pull complete
e8de7a394fb1: Pull complete
a731204f3022: Pull complete
6baca7c3de18: Pull complete
578e0d596415: Pull complete
fb3842188b26: Pull complete
4129552e9b6a: Pull complete
73192b026db6: Pull complete
029a2e32c482: Pull complete
Digest: sha256:b0b50addbb07bbb593635f2caaac37eeddc1a91d30947d614d627e8ed70a41c6
Status: Downloaded newer image for gisquick/django:vue
Pulling nginx (nginx:latest)...
latest: Pulling from library/nginx
8ec398bc0356: Pull complete
465560073b6f: Pull complete
f473f9fd0a8c: Pull complete
Digest: sha256:b2d89d0a210398b4d1120b3e3a7672c16a4ba09c2c4a0395f18b9f7999b768f2
Status: Downloaded newer image for nginx:latest
Creating fausto_go_1 ... 
Creating fausto_qgisserver_1 ... 
Creating fausto_qgisserver_1
Creating fausto_qgisserver_1 ... done
Creating fausto_django_1 ... 
Creating fausto_django_1 ... done
Creating fausto_nginx_1 ... 
Creating fausto_nginx_1 ... done
Attaching to fausto_go_1, fausto_qgisserver_1, fausto_django_1, fausto_nginx_1
qgisserver_1  | 2020-01-02 22:35:36,501 CRIT Supervisor running as root (no user in config file)
django_1      | 2020-01-02 22:35:39,414 INFO Set uid to user 0 succeeded
django_1      | 2020-01-02 22:35:39,422 INFO RPC interface 'supervisor' initialized
qgisserver_1  | 2020-01-02 22:35:36,503 INFO supervisord started with pid 1
nginx_1       | /bin/sh: 1: cannot open /etc/nginx/gisquick/conf.template: No such file
django_1      | 2020-01-02 22:35:39,422 CRIT Server 'unix_http_server' running without any HTTP authentication checking
qgisserver_1  | 2020-01-02 22:35:37,507 INFO spawned: 'Xvfb' with pid 8
django_1      | 2020-01-02 22:35:39,422 INFO supervisord started with pid 1
django_1      | 2020-01-02 22:35:40,425 INFO spawned: 'initialize' with pid 9
qgisserver_1  | 2020-01-02 22:35:37,512 INFO spawned: 'lighttpd' with pid 9
django_1      | 2020-01-02 22:35:40,431 INFO spawned: 'gunicorn' with pid 10
django_1      | [2020-01-02 22:35:40 +0000] [10] [INFO] Starting gunicorn 19.9.0
qgisserver_1  | 2020-01-02 22:35:38,681 INFO success: Xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
qgisserver_1  | 2020-01-02 22:35:38,681 INFO success: lighttpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
django_1      | 2020-01-02 22:35:40,765 INFO success: initialize entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
django_1      | [2020-01-02 22:35:40 +0000] [10] [INFO] Listening at: http://0.0.0.0:8000 (10)
django_1      | [2020-01-02 22:35:40 +0000] [10] [INFO] Using worker: sync
django_1      | [2020-01-02 22:35:40 +0000] [14] [INFO] Booting worker with pid: 14
django_1      | [2020-01-02 22:35:40 +0000] [16] [INFO] Booting worker with pid: 16
django_1      | 2020-01-02 22:35:42,035 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
django_1      | 2020-01-02 22:35:42,035 INFO exited: initialize (exit status 0; expected)
fausto_nginx_1 exited with code 2
nginx_1       | /bin/sh: 1: cannot open /etc/nginx/gisquick/conf.template: No such file
`

**Comment by marcel-dancak** [comment]
Hi,
currently there are quite significant changes in progress, and soon whole deployment will be different. It would be better if you could wait for couple of days, because troubleshooting something that will be obsolete very soon can be waste of time.

But if you would like to try it anyway right now, make sure that this folder https://github.com/gislab-npo/gisquick/tree/master/docker/nginx-conf is located at same level as docker-compose.yml file

**Comment by marcel-dancak** [comment]
Information about deployment was moved into new repository https://github.com/gislab-npo/gisquick-cli

You should be able to setup local deployment by following instructions in its README, with latest Docker images from Docker Hub.
