### ISSUE TITLE
Internal server error for demo 

### ISSUE THREAD

**Issue by CorentinLemaitre** [gislab-npo/gisquick#90]
Hello,
This issue is about the website for demo project, not about GisQuick code itself. I hope I have chosen the good repository to report this issue. 

I have tried to access to the demo using [link on the website](https://projects.gisquick.org/?PROJECT=user1/prague/prague) and there is a server error. 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)` 

Hope it will be helpful.

**Comment by marcel-dancak** [comment]
Hi,

our public server was running out of resources (disk storage) for a couple of times in last days. It should be working right now, but unfortunately it can happen again, if we don't allocate more resources.

Thank you for reporting issue
