### ISSUE TITLE
Verification email does not have target in button

### ISSUE THREAD

**Issue by barasoukup** [gislab-npo/gisquick#94]
<p>
  Welcome to <a class="link" href="http://test3.pir-test.eu/accounts/activate/?uid=OQ&token=5h1-69f874e3a91b095fe561">Gisquick!</a>
  To activate your account, please click on the following button
  <a
    class="md-button raised primary"
    href=""
  >
    Activate account
  </a>
</p>
<br />
<p>If you received this email in error, you can safely ignore this email.</p>

<p>
  <small>
    If you can't get the button to work, paste this link into your browser:
    http://test3.pir-test.eu/accounts/activate/?uid=OQ&token=5h1-69f874e3a91b095fe561
</small>
</p>

**Comment by marcel-dancak** [comment]
I think this was fixed some time ago here https://github.com/gislab-npo/gisquick/commit/b5c93e2b0b6d9574af30b598055fbc5a4d0fdd9e

I just didn't build and upload a new docker images for loner time, but I have just updated them.
